Repository MinWonHaeSo/ESC_SERVER, pull requests merged in 2022-12, with the labels that each got.

#12 Feat - Stadium : 체육관 아이템 등록/추가/삭제 구현
  src/main/java/com/minwonhaeso/esc/stadium/controller/StadiumController.java
  src/main/java/com/minwonhaeso/esc/stadium/dto/CreateStadiumDto.java
  src/main/java/com/minwonhaeso/esc/stadium/dto/CreateStadiumItemDto.java
  src/main/java/com/minwonhaeso/esc/stadium/dto/UpdateStadiumDto.java
  src/main/java/com/minwonhaeso/esc/stadium/entity/Stadium.java
  src/main/java/com/minwonhaeso/esc/stadium/entity/StadiumItem.java
  src/main/java/com/minwonhaeso/esc/stadium/repository/StadiumItemRepository.java
  src/main/java/com/minwonhaeso/esc/stadium/service/StadiumService.java
  src/main/java/com/minwonhaeso/esc/stadium/type/StadiumItemStatus.java
Labels: enhancement

#17 Feat - OAuth2 JWT 토큰 발급
  src/main/java/com/minwonhaeso/esc/error/exception/AuthException.java
  src/main/java/com/minwonhaeso/esc/error/handler/GlobalExceptionHandler.java
  src/main/java/com/minwonhaeso/esc/error/type/AuthErrorCode.java
  src/main/java/com/minwonhaeso/esc/member/controller/MemberController.java
  src/main/java/com/minwonhaeso/esc/security/SecurityConfig.java
  src/main/java/com/minwonhaeso/esc/security/auth/PrincipalDetails.java
  src/main/java/com/minwonhaeso/esc/security/auth/jwt/JwtTokenUtil.java
  src/main/java/com/minwonhaeso/esc/security/auth/redis/CacheConfig.java
  src/main/java/com/minwonhaeso/esc/security/oauth2/handler/OAuth2SuccessHandler.java
  src/main/java/com/minwonhaeso/esc/security/oauth2/service/CustomerOAuth2MemberService.java
Labels: ✨ Feature

#18 Feat - Stadium : 위도 경도 기반 가까운 체육관 조회(Querydsl)
  .gitignore
  build.gradle
  src/main/java/com/minwonhaeso/esc/common/config/QuerydslConfiguration.java
  src/main/java/com/minwonhaeso/esc/stadium/controller/StadiumManagerController.java
  src/main/java/com/minwonhaeso/esc/stadium/controller/StadiumUserController.java
  src/main/java/com/minwonhaeso/esc/stadium/model/dto/CreateStadiumDto.java
  src/main/java/com/minwonhaeso/esc/stadium/model/dto/CreateStadiumItemDto.java
  src/main/java/com/minwonhaeso/esc/stadium/model/dto/StadiumResponseDto.java
  src/main/java/com/minwonhaeso/esc/stadium/model/dto/UpdateStadiumDto.java
  src/main/java/com/minwonhaeso/esc/stadium/model/entity/Stadium.java
  src/main/java/com/minwonhaeso/esc/stadium/model/entity/StadiumImg.java
  src/main/java/com/minwonhaeso/esc/stadium/model/entity/StadiumItem.java
  src/main/java/com/minwonhaeso/esc/stadium/model/entity/StadiumTag.java
  src/main/java/com/minwonhaeso/esc/stadium/model/type/StadiumItemStatus.java
  src/main/java/com/minwonhaeso/esc/stadium/repository/StadiumImgRepository.java
  src/main/java/com/minwonhaeso/esc/stadium/repository/StadiumItemRepository.java
  src/main/java/com/minwonhaeso/esc/stadium/repository/StadiumRepository.java
  src/main/java/com/minwonhaeso/esc/stadium/repository/StadiumRepositorySupport.java
  src/main/java/com/minwonhaeso/esc/stadium/repository/StadiumTagRepository.java
  src/main/java/com/minwonhaeso/esc/stadium/service/StadiumService.java
  src/main/java/com/minwonhaeso/esc/stadium/util/LocationUtils.java
Labels: ✨ Feature, 🔨 Refactor

#21 Feat - OAuth2 JWT 토큰 발급 로직 변경
  src/main/java/com/minwonhaeso/esc/security/oauth2/handler/OAuth2SuccessHandler.java
  src/main/java/com/minwonhaeso/esc/security/oauth2/util/CookieUtil.java
Labels: ✨ Feature, 🔨 Refactor

#22 Feat - Stadium : Controller, Dto Swagger API 문서 코드 작성
  src/main/java/com/minwonhaeso/esc/stadium/controller/StadiumManagerController.java
  src/main/java/com/minwonhaeso/esc/stadium/controller/StadiumUserController.java
  src/main/java/com/minwonhaeso/esc/stadium/model/dto/CreateStadiumDto.java
  src/main/java/com/minwonhaeso/esc/stadium/model/dto/CreateStadiumItemDto.java
  src/main/java/com/minwonhaeso/esc/stadium/model/dto/StadiumResponseDto.java
  src/main/java/com/minwonhaeso/esc/stadium/model/dto/UpdateStadiumDto.java
  src/main/java/com/minwonhaeso/esc/stadium/model/entity/Stadium.java
Labels: 🏷️ Enhancement

#24 Feat - Auth 부분적인 오류 수정 및 테스트코드 작성
  src/main/java/com/minwonhaeso/esc/member/model/dto/LoginDto.java
  src/main/java/com/minwonhaeso/esc/member/model/entity/Member.java
  src/main/java/com/minwonhaeso/esc/member/model/type/MemberStatus.java
  src/main/java/com/minwonhaeso/esc/member/service/MemberService.java
  src/main/java/com/minwonhaeso/esc/security/auth/AuthUtil.java
  src/test/java/com/minwonhaeso/esc/member/service/MemberServiceTest.java
  src/test/java/com/minwonhaeso/esc/member/service/MemberServiceWithPrincipalTest.java
Labels: 🏷️ Enhancement, ✅ Test

#34 Fix: 이미지 Entity 수정 및 DTO 구조 변경
  .gitignore
  build.gradle
  src/main/java/com/minwonhaeso/esc/member/service/CustomerMemberDetailsService.java
  src/main/java/com/minwonhaeso/esc/stadium/controller/StadiumManagerController.java
  src/main/java/com/minwonhaeso/esc/stadium/model/dto/StadiumDto.java
  src/main/java/com/minwonhaeso/esc/stadium/model/dto/StadiumImgDto.java
  src/main/java/com/minwonhaeso/esc/stadium/model/dto/StadiumItemDto.java
  src/main/java/com/minwonhaeso/esc/stadium/model/dto/StadiumResponseDto.java
  src/main/java/com/minwonhaeso/esc/stadium/model/dto/StadiumTagDto.java
  src/main/java/com/minwonhaeso/esc/stadium/model/dto/UpdateStadiumDto.java
  src/main/java/com/minwonhaeso/esc/stadium/model/entity/Stadium.java
  src/main/java/com/minwonhaeso/esc/stadium/model/entity/StadiumImg.java
  src/main/java/com/minwonhaeso/esc/stadium/model/entity/StadiumItem.java
  src/main/java/com/minwonhaeso/esc/stadium/repository/StadiumRepository.java
  src/main/java/com/minwonhaeso/esc/stadium/service/StadiumService.java
Labels: 🔨 Refactor

#40 feat - auth
  src/main/java/com/minwonhaeso/esc/member/model/dto/InfoDto.java
  src/main/java/com/minwonhaeso/esc/member/model/dto/LoginDto.java
  src/main/java/com/minwonhaeso/esc/member/service/CustomerMemberDetailsService.java
  src/main/java/com/minwonhaeso/esc/security/auth/PrincipalDetail.java
  src/main/java/com/minwonhaeso/esc/security/auth/jwt/JwtTokenUtil.java
  src/main/java/com/minwonhaeso/esc/security/auth/redis/CacheConfig.java
  src/main/java/com/minwonhaeso/esc/security/oauth2/service/CustomerOAuth2MemberService.java
Labels: 🏷️ Enhancement

#41 Refactor : 전체적인 리팩토링 진행
  src/main/java/com/minwonhaeso/esc/config/CacheConfig.java
  src/main/java/com/minwonhaeso/esc/config/ElasticsearchConfig.java
  src/main/java/com/minwonhaeso/esc/config/QuerydslConfiguration.java
  src/main/java/com/minwonhaeso/esc/config/SwaggerConfig.java
  src/main/java/com/minwonhaeso/esc/mail/MailService.java
  src/main/java/com/minwonhaeso/esc/member/controller/MemberController.java
  src/main/java/com/minwonhaeso/esc/member/model/dto/SignDto.java
  src/main/java/com/minwonhaeso/esc/member/model/entity/Member.java
  src/main/java/com/minwonhaeso/esc/member/service/MemberService.java
  src/main/java/com/minwonhaeso/esc/security/auth/PrincipalDetail.java
  src/main/java/com/minwonhaeso/esc/security/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/com/minwonhaeso/esc/security/oauth2/handler/OAuth2SuccessHandler.java
  src/main/java/com/minwonhaeso/esc/stadium/controller/StadiumManagerController.java
  src/main/java/com/minwonhaeso/esc/util/AuthUtil.java
  src/main/java/com/minwonhaeso/esc/util/JwtTokenUtil.java
  src/main/java/com/minwonhaeso/esc/util/LocationUtils.java
Labels: 🏷️ Enhancement

#44 Fix : OAuth2 JWT 로직 변경 (Issue #43)
  src/main/java/com/minwonhaeso/esc/member/controller/MemberController.java
  src/main/java/com/minwonhaeso/esc/member/controller/MemberProfileController.java
  src/main/java/com/minwonhaeso/esc/member/model/dto/CPasswordDto.java
  src/main/java/com/minwonhaeso/esc/member/model/dto/OAuthDto.java
  src/main/java/com/minwonhaeso/esc/member/service/MemberService.java
  src/main/java/com/minwonhaeso/esc/security/oauth2/handler/OAuth2SuccessHandler.java
  src/main/java/com/minwonhaeso/esc/security/oauth2/service/CustomerOAuth2MemberService.java
  src/main/java/com/minwonhaeso/esc/security/oauth2/util/CookieUtil.java
Labels: 🏷️ Enhancement, 🔨 Refactor

#45 Fix : 피드백 반영, UI Test 후 리팩터링 진행
  src/main/java/com/minwonhaeso/esc/member/service/CustomerMemberDetailsService.java
  src/main/java/com/minwonhaeso/esc/security/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/com/minwonhaeso/esc/security/auth/jwt/JwtExpirationEnums.java
  src/main/java/com/minwonhaeso/esc/stadium/controller/StadiumManagerController.java
  src/main/java/com/minwonhaeso/esc/stadium/controller/StadiumUserController.java
  src/main/java/com/minwonhaeso/esc/stadium/model/dto/StadiumDto.java
  src/main/java/com/minwonhaeso/esc/stadium/model/dto/StadiumItemDto.java
  src/main/java/com/minwonhaeso/esc/stadium/model/dto/StadiumResponseDto.java
  src/main/java/com/minwonhaeso/esc/stadium/model/entity/Stadium.java
  src/main/java/com/minwonhaeso/esc/stadium/model/entity/StadiumDocument.java
  src/main/java/com/minwonhaeso/esc/stadium/model/entity/StadiumItem.java
  src/main/java/com/minwonhaeso/esc/stadium/service/StadiumSearchService.java
  src/main/java/com/minwonhaeso/esc/stadium/service/StadiumService.java
Labels: 🔨 Refactor

#47 Feat : 예약 도메인 셋팅(Model, Controller, Service, Repository)
  src/main/java/com/minwonhaeso/esc/stadium/controller/StadiumReservationController.java
  src/main/java/com/minwonhaeso/esc/stadium/model/dto/StadiumReservationDto.java
  src/main/java/com/minwonhaeso/esc/stadium/model/entity/StadiumReservation.java
  src/main/java/com/minwonhaeso/esc/stadium/model/entity/StadiumReservationCancel.java
  src/main/java/com/minwonhaeso/esc/stadium/model/entity/StadiumReservationItem.java
  src/main/java/com/minwonhaeso/esc/stadium/model/type/PaymentType.java
  src/main/java/com/minwonhaeso/esc/stadium/model/type/StadiumReservationStatus.java
  src/main/java/com/minwonhaeso/esc/stadium/repository/StadiumReservationCancelRepository.java
  src/main/java/com/minwonhaeso/esc/stadium/repository/StadiumReservationItemRepository.java
  src/main/java/com/minwonhaeso/esc/stadium/repository/StadiumReservationRepository.java
  src/main/java/com/minwonhaeso/esc/stadium/service/StadiumReservationService.java
Labels: ✨ Feature

#48 Feat : 리뷰 도메인 셋팅 및 회원 관련 리팩토링
  src/main/java/com/minwonhaeso/esc/member/model/dto/InfoDto.java
  src/main/java/com/minwonhaeso/esc/member/model/dto/LoginDto.java
  src/main/java/com/minwonhaeso/esc/member/model/dto/OAuthDto.java
  src/main/java/com/minwonhaeso/esc/member/model/dto/SignDto.java
  src/main/java/com/minwonhaeso/esc/member/service/MemberService.java
  src/main/java/com/minwonhaeso/esc/review/controller/ReviewController.java
  src/main/java/com/minwonhaeso/esc/review/model/dto/ReviewDto.java
  src/main/java/com/minwonhaeso/esc/review/model/entity/Review.java
  src/main/java/com/minwonhaeso/esc/review/repository/ReviewRepository.java
  src/main/java/com/minwonhaeso/esc/review/service/ReviewService.java
  src/main/java/com/minwonhaeso/esc/stadium/model/entity/Stadium.java
Labels: ✨ Feature, 🔨 Refactor

#50 Feat : 리뷰 CRUD 구현
  src/main/java/com/minwonhaeso/esc/error/exception/ReviewException.java
  src/main/java/com/minwonhaeso/esc/error/type/ReviewErrorCode.java
  src/main/java/com/minwonhaeso/esc/review/controller/ReviewController.java
  src/main/java/com/minwonhaeso/esc/review/model/dto/ReviewDto.java
  src/main/java/com/minwonhaeso/esc/review/model/entity/Review.java
  src/main/java/com/minwonhaeso/esc/review/repository/ReviewRepository.java
  src/main/java/com/minwonhaeso/esc/review/service/ReviewService.java
  src/main/java/com/minwonhaeso/esc/stadium/repository/StadiumReservationRepository.java
Labels: ✨ Feature, 📃 Docs

#52 Feat : 체육관 예약 API 기능 구현 (7 / 10) #51
  build.gradle
  src/main/java/com/minwonhaeso/esc/EscServerApplication.java
  src/main/java/com/minwonhaeso/esc/config/SwaggerConfig.java
  src/main/java/com/minwonhaeso/esc/error/exception/StadiumException.java
  src/main/java/com/minwonhaeso/esc/error/handler/GlobalExceptionHandler.java
  src/main/java/com/minwonhaeso/esc/error/type/StadiumErrorCode.java
  src/main/java/com/minwonhaeso/esc/stadium/controller/StadiumReservationController.java
  src/main/java/com/minwonhaeso/esc/stadium/controller/StadiumUserController.java
  src/main/java/com/minwonhaeso/esc/stadium/facade/RedissonLockReservingTimeFacade.java
  src/main/java/com/minwonhaeso/esc/stadium/model/dto/StadiumDto.java
  src/main/java/com/minwonhaeso/esc/stadium/model/dto/StadiumInfoResponseDto.java
  src/main/java/com/minwonhaeso/esc/stadium/model/dto/StadiumItemDto.java
  src/main/java/com/minwonhaeso/esc/stadium/model/dto/StadiumReservationDto.java
  src/main/java/com/minwonhaeso/esc/stadium/model/dto/StadiumResponseDto.java
  src/main/java/com/minwonhaeso/esc/stadium/model/entity/Stadium.java
  src/main/java/com/minwonhaeso/esc/stadium/model/entity/StadiumItem.java
  src/main/java/com/minwonhaeso/esc/stadium/model/entity/StadiumReservation.java
  src/main/java/com/minwonhaeso/esc/stadium/model/entity/StadiumReservationCancel.java
  src/main/java/com/minwonhaeso/esc/stadium/model/entity/StadiumReservationItem.java
  src/main/java/com/minwonhaeso/esc/stadium/model/type/ReservingTime.java
  src/main/java/com/minwonhaeso/esc/stadium/repository/StadiumReservationItemRepository.java
  src/main/java/com/minwonhaeso/esc/stadium/repository/StadiumReservationRepository.java
  src/main/java/com/minwonhaeso/esc/stadium/service/StadiumReservationService.java
  src/main/java/com/minwonhaeso/esc/stadium/service/StadiumService.java
  src/main/java/com/minwonhaeso/esc/util/HolidayUtil.java
Labels: ✨ Feature, 🔨 Refactor

#54 Feat : 찜하기 목록 조회 구현
  src/main/java/com/minwonhaeso/esc/member/controller/MemberController.java
  src/main/java/com/minwonhaeso/esc/member/service/MemberService.java
  src/main/java/com/minwonhaeso/esc/security/auth/jwt/JwtExpirationEnums.java
  src/main/java/com/minwonhaeso/esc/stadium/controller/StadiumLikeController.java
  src/main/java/com/minwonhaeso/esc/stadium/model/dto/StadiumLikeResponseDto.java
  src/main/java/com/minwonhaeso/esc/stadium/model/entity/StadiumLike.java
  src/main/java/com/minwonhaeso/esc/stadium/repository/StadiumLikeRepository.java
  src/main/java/com/minwonhaeso/esc/stadium/service/StadiumLikeService.java
Labels: 🏷️ Enhancement, 🔨 Refactor

#59 Fix : 리뷰 API 수정 및 알림 기능 구현 #57
  src/main/java/com/minwonhaeso/esc/member/model/dto/InfoDto.java
  src/main/java/com/minwonhaeso/esc/member/model/dto/LoginDto.java
  src/main/java/com/minwonhaeso/esc/member/model/dto/OAuthDto.java
  src/main/java/com/minwonhaeso/esc/member/service/MemberService.java
  src/main/java/com/minwonhaeso/esc/notification/model/type/NotificationType.java
  src/main/java/com/minwonhaeso/esc/review/model/dto/ReviewDto.java
  src/main/java/com/minwonhaeso/esc/review/model/entity/Review.java
  src/main/java/com/minwonhaeso/esc/review/service/ReviewService.java
Labels: 🏷️ Enhancement, ✨ Feature

#58 Fix : UI Test 관련 오류 수정
  src/main/java/com/minwonhaeso/esc/error/type/StadiumErrorCode.java
  src/main/java/com/minwonhaeso/esc/member/controller/MemberController.java
  src/main/java/com/minwonhaeso/esc/member/controller/MemberProfileController.java
  src/main/java/com/minwonhaeso/esc/member/service/MemberService.java
  src/main/java/com/minwonhaeso/esc/review/model/dto/ReviewDto.java
  src/main/java/com/minwonhaeso/esc/stadium/controller/StadiumLikeController.java
  src/main/java/com/minwonhaeso/esc/stadium/controller/StadiumManagerController.java
  src/main/java/com/minwonhaeso/esc/stadium/controller/StadiumReservationController.java
  src/main/java/com/minwonhaeso/esc/stadium/model/dto/StadiumDto.java
  src/main/java/com/minwonhaeso/esc/stadium/model/dto/StadiumImgDto.java
  src/main/java/com/minwonhaeso/esc/stadium/model/dto/StadiumInfoResponseDto.java
  src/main/java/com/minwonhaeso/esc/stadium/model/dto/StadiumItemDto.java
  src/main/java/com/minwonhaeso/esc/stadium/model/dto/StadiumLikeRequestDto.java
  src/main/java/com/minwonhaeso/esc/stadium/model/dto/StadiumReservationDto.java
  src/main/java/com/minwonhaeso/esc/stadium/model/dto/StadiumResponseDto.java
  src/main/java/com/minwonhaeso/esc/stadium/model/dto/StadiumTagDto.java
  src/main/java/com/minwonhaeso/esc/stadium/model/entity/Stadium.java
  src/main/java/com/minwonhaeso/esc/stadium/model/entity/StadiumImg.java
  src/main/java/com/minwonhaeso/esc/stadium/model/entity/StadiumItem.java
  src/main/java/com/minwonhaeso/esc/stadium/model/entity/StadiumTag.java
  src/main/java/com/minwonhaeso/esc/stadium/model/type/ReservingTime.java
  src/main/java/com/minwonhaeso/esc/stadium/service/StadiumLikeService.java
  src/main/java/com/minwonhaeso/esc/stadium/service/StadiumReservationService.java
  src/main/java/com/minwonhaeso/esc/stadium/service/StadiumService.java
  src/test/java/com/minwonhaeso/esc/stadium/config/QuerydslTestConfiguration.java
Labels: 🏷️ Enhancement, 🔨 Refactor

#62 Fix : ReviewDto 수정
  build.gradle
  src/main/java/com/minwonhaeso/esc/review/controller/ReviewController.java
  src/main/java/com/minwonhaeso/esc/review/model/dto/ReviewDto.java
  src/main/java/com/minwonhaeso/esc/review/model/entity/Review.java
  src/main/java/com/minwonhaeso/esc/review/repository/ReviewRepository.java
  src/main/java/com/minwonhaeso/esc/review/service/ReviewService.java
Labels: 🔨 Refactor

#63 Fix : 체육관 예약 관련 API 수정 보완
  build.gradle
  src/main/java/com/minwonhaeso/esc/stadium/controller/StadiumReservationController.java
  src/main/java/com/minwonhaeso/esc/stadium/model/dto/StadiumInfoResponseDto.java
  src/main/java/com/minwonhaeso/esc/stadium/model/dto/StadiumReservationDto.java
  src/main/java/com/minwonhaeso/esc/stadium/model/entity/Stadium.java
  src/main/java/com/minwonhaeso/esc/stadium/model/entity/StadiumReservation.java
  src/main/java/com/minwonhaeso/esc/stadium/model/type/ReservingTime.java
  src/main/java/com/minwonhaeso/esc/stadium/repository/StadiumReservationRepository.java
  src/main/java/com/minwonhaeso/esc/stadium/service/StadiumReservationService.java
  src/main/java/com/minwonhaeso/esc/stadium/service/StadiumService.java
  src/main/java/com/minwonhaeso/esc/util/HolidayUtil.java
Labels: 🏷️ Enhancement, 🔨 Refactor

#64 Feat - Payment
  src/main/java/com/minwonhaeso/esc/error/type/AuthErrorCode.java
  src/main/java/com/minwonhaeso/esc/member/model/dto/LoginDto.java
  src/main/java/com/minwonhaeso/esc/member/service/MemberService.java
  src/main/java/com/minwonhaeso/esc/stadium/controller/StadiumLikeController.java
  src/main/java/com/minwonhaeso/esc/stadium/model/dto/StadiumLikeResponseDto.java
  src/main/java/com/minwonhaeso/esc/stadium/model/dto/StadiumPaymentDto.java
  src/main/java/com/minwonhaeso/esc/stadium/model/entity/StadiumLike.java
  src/main/java/com/minwonhaeso/esc/stadium/model/entity/StadiumPayment.java
  src/main/java/com/minwonhaeso/esc/stadium/model/entity/StadiumReservation.java
  src/main/java/com/minwonhaeso/esc/stadium/repository/StadiumPaymentRepository.java
  src/main/java/com/minwonhaeso/esc/stadium/service/StadiumPaymentService.java
Labels: 🏷️ Enhancement

#65 Test : 리뷰 테스트 코드 작성 & 체육관 평점 스케줄링
  src/main/java/com/minwonhaeso/esc/review/controller/ReviewController.java
  src/main/java/com/minwonhaeso/esc/review/repository/ReviewRepository.java
  src/main/java/com/minwonhaeso/esc/review/service/ReviewService.java
  src/test/java/com/minwonhaeso/esc/review/service/ReviewServiceTest.java
Labels: ✨ Feature, 🔨 Refactor, ✅ Test

#70 Fix : Payment 및 예약 생성 로직 수정
  src/main/java/com/minwonhaeso/esc/member/controller/MemberController.java
  src/main/java/com/minwonhaeso/esc/member/controller/MemberProfileController.java
  src/main/java/com/minwonhaeso/esc/member/repository/redis/MemberEmailRepository.java
  src/main/java/com/minwonhaeso/esc/member/service/MemberService.java
  src/main/java/com/minwonhaeso/esc/stadium/controller/StadiumLikeController.java
  src/main/java/com/minwonhaeso/esc/stadium/controller/StadiumPaymentController.java
  src/main/java/com/minwonhaeso/esc/stadium/model/dto/StadiumPaymentDto.java
  src/main/java/com/minwonhaeso/esc/stadium/model/entity/StadiumPayment.java
  src/main/java/com/minwonhaeso/esc/stadium/model/entity/StadiumTag.java
  src/main/java/com/minwonhaeso/esc/stadium/repository/StadiumPaymentRepository.java
  src/main/java/com/minwonhaeso/esc/stadium/service/StadiumPaymentService.java
Labels: 🏷️ Enhancement, 🔨 Refactor

#68 Fix : Front 통합 테스트 관련 오류 수정
  src/main/java/com/minwonhaeso/esc/error/handler/GlobalExceptionHandler.java
  src/main/java/com/minwonhaeso/esc/error/type/AuthErrorCode.java
  src/main/java/com/minwonhaeso/esc/member/service/MemberService.java
  src/main/java/com/minwonhaeso/esc/security/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/com/minwonhaeso/esc/stadium/model/dto/StadiumDto.java
  src/main/java/com/minwonhaeso/esc/stadium/model/dto/StadiumInfoResponseDto.java
  src/main/java/com/minwonhaeso/esc/stadium/model/dto/StadiumLikeResponseDto.java
  src/main/java/com/minwonhaeso/esc/stadium/model/dto/StadiumReservationDto.java
  src/main/java/com/minwonhaeso/esc/stadium/model/entity/Stadium.java
  src/main/java/com/minwonhaeso/esc/stadium/repository/StadiumSearchRepository.java
  src/main/java/com/minwonhaeso/esc/stadium/service/StadiumPaymentService.java
  src/main/java/com/minwonhaeso/esc/stadium/service/StadiumReservationService.java
  src/main/java/com/minwonhaeso/esc/stadium/service/StadiumSearchService.java
Labels: 🦖 Bug, 🏷️ Enhancement, 🔨 Refactor

#71 Fix : Reservation, Notification UI Test 버그 수정
  .gitignore
  build.gradle
  src/main/java/com/minwonhaeso/esc/error/type/StadiumErrorCode.java
  src/main/java/com/minwonhaeso/esc/notification/model/type/NotificationType.java
  src/main/java/com/minwonhaeso/esc/notification/service/NotificationService.java
  src/main/java/com/minwonhaeso/esc/review/service/ReviewService.java
  src/main/java/com/minwonhaeso/esc/stadium/controller/StadiumManagerController.java
  src/main/java/com/minwonhaeso/esc/stadium/controller/StadiumReservationController.java
  src/main/java/com/minwonhaeso/esc/stadium/controller/StadiumUserController.java
  src/main/java/com/minwonhaeso/esc/stadium/model/entity/StadiumReservation.java
  src/main/java/com/minwonhaeso/esc/stadium/repository/StadiumReservationRepository.java
  src/main/java/com/minwonhaeso/esc/stadium/service/StadiumReservationService.java
  src/main/java/com/minwonhaeso/esc/stadium/service/StadiumSearchService.java
  src/test/java/com/minwonhaeso/esc/member/service/MemberServiceWithPrincipalTest.java
  src/test/java/com/minwonhaeso/esc/review/service/ReviewServiceTest.java
  src/test/java/com/minwonhaeso/esc/stadium/controller/StadiumManagerControllerTest.java
  src/test/java/com/minwonhaeso/esc/stadium/controller/StadiumUserControllerTest.java
  src/test/java/com/minwonhaeso/esc/stadium/service/StadiumReservationServiceTest.java
  src/test/java/com/minwonhaeso/esc/stadium/service/StadiumServiceTest.java
Labels: 🦖 Bug, 🏷️ Enhancement, 🔨 Refactor

#75 Test : ReviewController 테스트 코드 완료
  src/main/java/com/minwonhaeso/esc/error/type/ReviewErrorCode.java
  src/main/java/com/minwonhaeso/esc/review/model/dto/ReviewDto.java
  src/main/java/com/minwonhaeso/esc/review/repository/ReviewRepository.java
  src/main/java/com/minwonhaeso/esc/review/service/ReviewService.java
  src/test/java/com/minwonhaeso/esc/review/controller/ReviewControllerTest.java
  src/test/java/com/minwonhaeso/esc/review/service/ReviewServiceTest.java
Labels: 🔨 Refactor, ✅ Test

#80 Fix : Front 통합 테스트 관련 오류 수정
  src/main/java/com/minwonhaeso/esc/error/type/AuthErrorCode.java
  src/main/java/com/minwonhaeso/esc/error/type/StadiumErrorCode.java
  src/main/java/com/minwonhaeso/esc/member/controller/MemberProfileController.java
  src/main/java/com/minwonhaeso/esc/member/service/MemberService.java
  src/main/java/com/minwonhaeso/esc/stadium/controller/StadiumLikeController.java
  src/main/java/com/minwonhaeso/esc/stadium/model/dto/StadiumLikeResponseDto.java
  src/main/java/com/minwonhaeso/esc/stadium/model/dto/StadiumPaymentDto.java
  src/main/java/com/minwonhaeso/esc/stadium/repository/StadiumRepository.java
  src/main/java/com/minwonhaeso/esc/stadium/repository/StadiumRepositorySupport.java
  src/main/java/com/minwonhaeso/esc/stadium/repository/StadiumReservationRepository.java
  src/main/java/com/minwonhaeso/esc/stadium/service/StadiumLikeService.java
  src/main/java/com/minwonhaeso/esc/stadium/service/StadiumPaymentService.java
  src/test/java/com/minwonhaeso/esc/member/service/MemberServiceTest.java
  src/test/java/com/minwonhaeso/esc/member/service/MemberServiceWithPrincipalTest.java
  src/test/java/com/minwonhaeso/esc/review/service/ReviewServiceTest.java
  src/test/java/com/minwonhaeso/esc/stadium/service/StadiumLikeServiceTest.java
  src/test/java/com/minwonhaeso/esc/stadium/service/StadiumPaymentServiceTest.java
Labels: 🏷️ Enhancement, ✅ Test
